### Student list
GET localhost:8080/student/list

### Student by id
GET localhost:8080/student/get/32


### Student create
POST localhost:8080/student/create
Content-Type: application/json

{
  "name": "D",
  "surname": "B",
  "age": 23,
  "gender": "MALE",
  "level": "4"
}


### Student create
POST localhost:8080/student/create/all
Content-Type: application/json

[
  {
    "name": "Name1",
    "surname": "Toshmatov"
  },
  {
    "name": "Name2",
    "surname": "Toshmatov"
  },
  {
    "name": "Name3",
    "surname": "Toshmatov"
  }
]

### Student update
PUT localhost:8080/student/update/2
Content-Type: application/json

{
  "name": "V",
  "surname": "Valiyeva",
  "age": 19,
  "gender": "FEMALE",
  "level": "1"
}

### Student delete
DELETE localhost:8080/student/delete/2


### Student by id
GET localhost:8080/student/test

###
GET  localhost:8080/student/list-by-given-date/2023-04-05T14:21:33.844902

###

GET localhost:8080/student/list-by-given-dates
Content-Type: application/json

{
  "fromDate": "2023-04-05T14:21:33.844902",
  "toDate": "2023-04-05T16:15:32.89926"
}